### ISSUE TITLE
Split INI parser into seperate package

### ISSUE THREAD

**Issue by rob-deutsch** [speedy-tuner/speedy-tuner-cloud#155]
Hi, I would like to add to the INI parser (both `parser/ini.ts` and `types/config.ts`) but it would be easier to do if they resided in a seperate package.

I could seperate them myself (of course) but I figured it might be easier to do it under the speedy-tuner banner?

**Comment by karniv00l** [comment]
Hi Rob, 

Thanks for getting interested in the project. 

Since this project will act as a base for the desktop (electron) and possibly mobile (react native) app, there is a lot of code that has to be extracted into standalone packages, my plan is to host them here on github under this organization. 

If you're eager to help just give me couple of days and I will prepare them for you.

**Comment by adbancroft** [comment]
How about we (I?) add a Javascript implementation of [TunerStudioIniParser](https://github.com/adbancroft/TunerStudioIniParser)?

It's lark based & there is a [JS Lark implementation](https://github.com/lark-parser/Lark.js). They can share the same lark grammars, which is where most of the heavy lifting is.

**Comment by adbancroft** [comment]
It would require pushing logic/parsing from the [current speedy-tuner parser](https://github.com/speedy-tuner/speedy-tuner-cloud/blob/master/src/parser/ini.ts) into the lark grammar.

**Comment by rob-deutsch** [comment]
@karniv00l, I am eager to help, but there's no rush to split them out. I am currently working on a serial communications package.

@adbancroft, good to see you here! It's great to see a community forming around some mutual goals. I've had the opportunity to play with both speedy-tuner-cloud and TunerStudioIniParser this week, and I can share some views of pros/cons of each.

As you've noted, TunerStudioIniParser is portable because it uses the Lark files, and it also has a full-featured pre-processor. A significant advantage of speedy-tuner-cloud, though, is that the data structure it outputs is more useful and easy to understand.

**Comment by adbancroft** [comment]
@rob-deutsch My first go at parsing TS INI files looked very much like the speedy-tuner-cloud parsing code & data structures. I.e. custom code & data structures for many of the line types. You can see it [here](https://github.com/adbancroft/speeduino/blob/generate_sendpageascii/build/read_tsini.py).

I went away from this approach as complexity rises very quickly as I began to support more & more INI details.

TunerStudioIniParser is *very* early in it's lifecycle - I've only worked on it for a few weeks - and it already does more than my first pass at INI parsing.

The Lark transformer framework can output anything we want - it's just a matter of agreeing the direction. We can even have the best of both worlds: a lower level Lark tree & a higher level of abstraction (custom data structures) generated via a transformer.

**Comment by adbancroft** [comment]
@rob-deutsch I created an [example](https://github.com/adbancroft/TunerStudioIniParser/tree/example_custom_class). Run the `test_speeduino` test - you'll see it prints a python dictionary instead of the Lark tree structure.

**Comment by karniv00l** [comment]
@rob-deutsch I will create new repositories and set up proper pipelines.

@adbancroft INI parser is a definitely a cumbersome part of the project. Sure I'm opened for better alternatives. As far as I understand, if we make a good parser once, it should hold up in the future since the structure doesn't change. Feel free to continue this topic when I move the parser out of this repo.

---

Deciding on output data structure is a definitely topic on its own and I believe needs a proper discussion since it will be consumed by multiple apps / clients.

**Comment by karniv00l** [comment]
As promised:

- Parser: https://github.com/speedy-tuner/ini
- Types: https://github.com/speedy-tuner/types
